apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poc4-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: iamsnaaz/poc4
    argocd-image-updater.argoproj.io/iamsnaaz.poc4.update-strategy: latest
spec:
  project: default
  source:
    repoURL: https://github.com/iamsnaaz/POC4
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
