apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poc4
  template:
    metadata:
      labels:
        app: poc4
    spec:
      containers:
      - name: poc4
        image: iamsnaaz/my-docker-registry:poc4
        ports:
        - containerPort: 8080
