apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc4
spec:
  replicas: 3
  selector:
    matchLabels:
      app: poc4
  template:
    metadata:
      labels:
        app: poc4
    spec:
      containers:
      - name: poc4
        image: iamsnaaz/poc4
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
